__author__ = 'pmpro'
# coding=utf-8

ADAPTER = "mysql"
DB_HOST = "127.0.0.1"
DB_PORT = 3306
DB_USER = "CHANGE ME"
DB_PASSWORD = "CHANGE ME"
DB_NAME = "CHANGE ME"
DB_CHARSET = "utf8mb4"
NUMBER_OF_ROWS = 10
FILL_RELATIONS = True